### ISSUE TITLE
Building Fails With 3 Errors

### ISSUE THREAD

**Issue by Phate6660** [tbrand/dystopia#23]
Hello, I just came over here from your Reddit post. I was pretty curious about this, as Tor is something I use daily and Rust is my new favorite programming language. So I was going to build it just to look at it a bit, but it failed with 3 errors.

```error: linking with `cc` failed: exit code: 1```
    Note: This one had a lot of various paths after it, so if you need any of that output let me know.

```error: aborting due to previous error```

```error: Could not compile `dytp`.```

**Comment by tbrand** [comment]
Nice! What OS are you using?
Dystopia uses https://github.com/diesel-rs/diesel as ORM.
May be you need to install PostgreSQL backend.
https://github.com/diesel-rs/diesel/blob/master/guide_drafts/backend_installation.md

**Comment by Phate6660** [comment]
> What OS are you using?

Currently on Arch Linux.

> May be you need to install PostgreSQL backend.

I'll install that then, and see if it fails to build again.

**Comment by tbrand** [comment]
Cool :+1:

**Comment by Phate6660** [comment]
Build succeeded. Thanks. :+1:

**Comment by tbrand** [comment]
Awesome! :+1:

If you try to construct the Dystopia's network on local PC, you could follow the steps on [Getting Started](https://github.com/tbrand/dystopia/wiki/Getting-Started).

Let me close the issue.
Please open another one if you have any questions!

Thanks.
